export const DATA = {
  categories: [
    {
      id: 1,
      name: 'Action (set 1)',
      urlToImg: './assets/img/categories/dance.jpg',
    },
    {
      id: 2,
      name: 'Action (set 2)',
      urlToImg: './assets/img/categories/swim.jpg',
    },
    {
      id: 3,
      name: 'Action (set 3)',
      urlToImg: './assets/img/categories/build.jpg',
    },
    {
      id: 4,
      name: 'Adjectives',
      urlToImg: './assets/img/categories/fast.jpg',
    },
    {
      id: 5,
      name: 'Animals (set 1)',
      urlToImg: './assets/img/categories/cat.jpg',
    },
    {
      id: 6,
      name: 'Animals (set 2)',
      urlToImg: './assets/img/categories/bird.jpg',
    },
    {
      id: 7,
      name: 'Clothes',
      urlToImg: './assets/img/categories/blouse.jpg',
    },
    {
      id: 8,
      name: 'Emotions',
      urlToImg: './assets/img/categories/happy.jpg',
    },
  ],
  words: [
    {
      categoryID: 1,
      word: 'Cry',
      translation: 'Плакать',
      urlToAudio: './assets/audio/cry.mp3',
      urlToImg: './assets/img/categories/cry.jpg',
    },
    {
      categoryID: 1,
      word: 'Dance',
      translation: 'Танцевать',
      urlToAudio: './assets/audio/dance.mp3',
      urlToImg: './assets/img/categories/dance.jpg',
    },
    {
      categoryID: 1,
      word: 'Dive',
      translation: 'Нырять',
      urlToAudio: './assets/audio/dive.mp3',
      urlToImg: './assets/img/categories/dive.jpg',
    },
    {
      categoryID: 1,
      word: 'Draw',
      translation: 'Рисовать',
      urlToAudio: './assets/audio/draw.mp3',
      urlToImg: './assets/img/categories/draw.jpg',
    },
    {
      categoryID: 1,
      word: 'Fish',
      translation: 'Ловить рыбу',
      urlToAudio: './assets/audio/fish.mp3',
      urlToImg: './assets/img/categories/fish.jpg',
    },
    {
      categoryID: 1,
      word: 'Fly',
      translation: 'Летать',
      urlToAudio: './assets/audio/fly.mp3',
      urlToImg: './assets/img/categories/fly.jpg',
    },
    {
      categoryID: 1,
      word: 'Hug',
      translation: 'Обнимать',
      urlToAudio: './assets/audio/hug.mp3',
      urlToImg: './assets/img/categories/hug.jpg',
    },
    {
      categoryID: 1,
      word: 'Jump',
      translation: 'Прыгать',
      urlToAudio: './assets/audio/jump.mp3',
      urlToImg: './assets/img/categories/jump.jpg',
    },
    {
      categoryID: 2,
      word: 'Open',
      translation: 'Открыть',
      urlToAudio: './assets/audio/open.mp3',
      urlToImg: './assets/img/categories/open.jpg',
    },
    {
      categoryID: 2,
      word: 'Play',
      translation: 'Играть',
      urlToAudio: './assets/audio/play.mp3',
      urlToImg: './assets/img/categories/play.jpg',
    },
    {
      categoryID: 2,
      word: 'Point',
      translation: 'Показать',
      urlToAudio: './assets/audio/point.mp3',
      urlToImg: './assets/img/categories/point.jpg',
    },
    {
      categoryID: 2,
      word: 'Ride',
      translation: 'Ездить',
      urlToAudio: './assets/audio/ride.mp3',
      urlToImg: './assets/img/categories/ride.jpg',
    },
    {
      categoryID: 2,
      word: 'Run',
      translation: 'Бежать',
      urlToAudio: './assets/audio/run.mp3',
      urlToImg: './assets/img/categories/run.jpg',
    },
    {
      categoryID: 2,
      word: 'Sing',
      translation: 'Петь',
      urlToAudio: './assets/audio/sing.mp3',
      urlToImg: './assets/img/categories/sing.jpg',
    },
    {
      categoryID: 2,
      word: 'Skip',
      translation: 'Прыгать',
      urlToAudio: './assets/audio/skip.mp3',
      urlToImg: './assets/img/categories/skip.jpg',
    },
    {
      categoryID: 2,
      word: 'Swim',
      translation: 'Плавать',
      urlToAudio: './assets/audio/swim.mp3',
      urlToImg: './assets/img/categories/swim.jpg',
    },
    {
      categoryID: 3,
      word: 'Argue',
      translation: 'Ссориться',
      urlToAudio: './assets/audio/argue.mp3',
      urlToImg: './assets/img/categories/argue.jpg',
    },
    {
      categoryID: 3,
      word: 'Build',
      translation: 'Строить',
      urlToAudio: './assets/audio/build.mp3',
      urlToImg: './assets/img/categories/build.jpg',
    },
    {
      categoryID: 3,
      word: 'Carry',
      translation: 'Нести',
      urlToAudio: './assets/audio/carry.mp3',
      urlToImg: './assets/img/categories/carry.png',
    },
    {
      categoryID: 3,
      word: 'Catch',
      translation: 'Словить',
      urlToAudio: './assets/audio/catch.mp3',
      urlToImg: './assets/img/categories/catch.jpg',
    },
    {
      categoryID: 3,
      word: 'Drive',
      translation: 'Водить',
      urlToAudio: './assets/audio/drive.mp3',
      urlToImg: './assets/img/categories/drive.jpg',
    },
    {
      categoryID: 3,
      word: 'Drop',
      translation: 'Упасть',
      urlToAudio: './assets/audio/drop.mp3',
      urlToImg: './assets/img/categories/drop.jpg',
    },
    {
      categoryID: 3,
      word: 'Pull',
      translation: 'Тянуть',
      urlToAudio: './assets/audio/pull.mp3',
      urlToImg: './assets/img/categories/pull.jpg',
    },
    {
      categoryID: 3,
      word: 'Push',
      translation: 'Толкать',
      urlToAudio: './assets/audio/push.mp3',
      urlToImg: './assets/img/categories/push.jpg',
    },
    {
      categoryID: 4,
      word: 'Big',
      translation: 'Большой',
      urlToAudio: './assets/audio/big.mp3',
      urlToImg: './assets/img/categories/big.jpg',
    },
    {
      categoryID: 4,
      word: 'Small',
      translation: 'Маленький',
      urlToAudio: './assets/audio/small.mp3',
      urlToImg: './assets/img/categories/small.jpg',
    },
    {
      categoryID: 4,
      word: 'Fast',
      translation: 'Быстрый',
      urlToAudio: './assets/audio/fast.mp3',
      urlToImg: './assets/img/categories/fast.jpg',
    },
    {
      categoryID: 4,
      word: 'Slow',
      translation: 'Медленный',
      urlToAudio: './assets/audio/slow.mp3',
      urlToImg: './assets/img/categories/slow.jpg',
    },
    {
      categoryID: 4,
      word: 'Friendly',
      translation: 'Дружелюбный',
      urlToAudio: './assets/audio/friendly.mp3',
      urlToImg: './assets/img/categories/friendly.jpg',
    },
    {
      categoryID: 4,
      word: 'Unfriendly',
      translation: 'Недружелюбный',
      urlToAudio: './assets/audio/unfriendly.mp3',
      urlToImg: './assets/img/categories/unfriendly.jpg',
    },
    {
      categoryID: 4,
      word: 'Young',
      translation: 'Молодой',
      urlToAudio: './assets/audio/young.mp3',
      urlToImg: './assets/img/categories/young.jpeg',
    },
    {
      categoryID: 4,
      word: 'Old',
      translation: 'Старый',
      urlToAudio: './assets/audio/old.mp3',
      urlToImg: './assets/img/categories/old.jpg',
    },
    {
      categoryID: 5,
      word: 'Cat',
      translation: 'Кот',
      urlToAudio: './assets/audio/point.mp3',
      urlToImg: './assets/img/categories/cat.jpg',
    },
    {
      categoryID: 5,
      word: 'Chick',
      translation: 'Цыплёнок',
      urlToAudio: './assets/audio/chick.mp3',
      urlToImg: './assets/img/categories/chick.jpg',
    },
    {
      categoryID: 5,
      word: 'Chicken',
      translation: 'Курица',
      urlToAudio: './assets/audio/chicken.mp3',
      urlToImg: './assets/img/categories/chicken.jpg',
    },
    {
      categoryID: 5,
      word: 'Dog',
      translation: 'Собака',
      urlToAudio: './assets/audio/dog.mp3',
      urlToImg: './assets/img/categories/dog.jpg',
    },
    {
      categoryID: 5,
      word: 'Horse',
      translation: 'Конь',
      urlToAudio: './assets/audio/horse.mp3',
      urlToImg: './assets/img/categories/horse.jpg',
    },
    {
      categoryID: 5,
      word: 'Pig',
      translation: 'Свинья',
      urlToAudio: './assets/audio/pig.mp3',
      urlToImg: './assets/img/categories/pig.jpg',
    },
    {
      categoryID: 5,
      word: 'Rabbit',
      translation: 'Кролик',
      urlToAudio: './assets/audio/rabbit.mp3',
      urlToImg: './assets/img/categories/rabbit.jpg',
    },
    {
      categoryID: 5,
      word: 'Sheep',
      translation: 'Овца',
      urlToAudio: './assets/audio/sheep.mp3',
      urlToImg: './assets/img/categories/sheep.jpg',
    },
    {
      categoryID: 6,
      word: 'Bird',
      translation: 'Птица',
      urlToAudio: './assets/audio/bird.mp3',
      urlToImg: './assets/img/categories/bird.jpg',
    },
    {
      categoryID: 6,
      word: 'Fish',
      translation: 'Рыба',
      urlToAudio: './assets/audio/fish.mp3',
      urlToImg: './assets/img/categories/fish1.jpg',
    },
    {
      categoryID: 6,
      word: 'Frog',
      translation: 'Лягушка',
      urlToAudio: './assets/audio/frog.mp3',
      urlToImg: './assets/img/categories/frog.jpg',
    },
    {
      categoryID: 6,
      word: 'Giraffe',
      translation: 'Жираф',
      urlToAudio: './assets/audio/giraffe.mp3',
      urlToImg: './assets/img/categories/giraffe.jpg',
    },
    {
      categoryID: 6,
      word: 'Lion',
      translation: 'Лев',
      urlToAudio: './assets/audio/lion.mp3',
      urlToImg: './assets/img/categories/lion.jpg',
    },
    {
      categoryID: 6,
      word: 'Mouse',
      translation: 'Мышь',
      urlToAudio: './assets/audio/mouse.mp3',
      urlToImg: './assets/img/categories/mouse.jpg',
    },
    {
      categoryID: 6,
      word: 'Turtle',
      translation: 'Черпаха',
      urlToAudio: './assets/audio/turtle.mp3',
      urlToImg: './assets/img/categories/turtle.jpg',
    },
    {
      categoryID: 6,
      word: 'Dolphin',
      translation: 'Дельфин',
      urlToAudio: './assets/audio/dolphin.mp3',
      urlToImg: './assets/img/categories/dolphin.jpg',
    },
    {
      categoryID: 7,
      word: 'Skirt',
      translation: 'Юбка',
      urlToAudio: './assets/audio/skirt.mp3',
      urlToImg: './assets/img/categories/skirt.jpg',
    },
    {
      categoryID: 7,
      word: 'Pants',
      translation: 'Штаны',
      urlToAudio: './assets/audio/pants.mp3',
      urlToImg: './assets/img/categories/pants.jpg',
    },
    {
      categoryID: 7,
      word: 'Blouse',
      translation: 'Блузка',
      urlToAudio: './assets/audio/blouse.mp3',
      urlToImg: './assets/img/categories/blouse.jpg',
    },
    {
      categoryID: 7,
      word: 'Dress',
      translation: 'Платье',
      urlToAudio: './assets/audio/dress.mp3',
      urlToImg: './assets/img/categories/dress.jpg',
    },
    {
      categoryID: 7,
      word: 'Boots',
      translation: 'Ботинки',
      urlToAudio: './assets/audio/boot.mp3',
      urlToImg: './assets/img/categories/boot.jpg',
    },
    {
      categoryID: 7,
      word: 'Shirt',
      translation: 'Майка',
      urlToAudio: './assets/audio/shirt.mp3',
      urlToImg: './assets/img/categories/shirt.jpg',
    },
    {
      categoryID: 7,
      word: 'Coat',
      translation: 'Пальто',
      urlToAudio: './assets/audio/coat.mp3',
      urlToImg: './assets/img/categories/coat.jpg',
    },
    {
      categoryID: 7,
      word: 'Shoes',
      translation: 'Туфли',
      urlToAudio: './assets/audio/shoe.mp3',
      urlToImg: './assets/img/categories/shoe.jpg',
    },
    {
      categoryID: 8,
      word: 'Sad',
      translation: 'Грустный',
      urlToAudio: './assets/audio/sad.mp3',
      urlToImg: './assets/img/categories/sad.jpg',
    },
    {
      categoryID: 8,
      word: 'Angry',
      translation: 'Злой',
      urlToAudio: './assets/audio/angry.mp3',
      urlToImg: './assets/img/categories/angry.jpg',
    },
    {
      categoryID: 8,
      word: 'Happy',
      translation: 'Счастливый',
      urlToAudio: './assets/audio/happy.mp3',
      urlToImg: './assets/img/categories/happy.jpg',
    },
    {
      categoryID: 8,
      word: 'Tired',
      translation: 'Уставший',
      urlToAudio: './assets/audio/tired.mp3',
      urlToImg: './assets/img/categories/tired.jpg',
    },
    {
      categoryID: 8,
      word: 'Surprised',
      translation: 'Удивлённый',
      urlToAudio: './assets/audio/surprised.mp3',
      urlToImg: './assets/img/categories/surprised.jpg',
    },
    {
      categoryID: 8,
      word: 'Scared',
      translation: 'Напуганный',
      urlToAudio: './assets/audio/scared.mp3',
      urlToImg: './assets/img/categories/scared.jpg',
    },
    {
      categoryID: 8,
      word: 'Smile',
      translation: 'Улыбка',
      urlToAudio: './assets/audio/smile.mp3',
      urlToImg: './assets/img/categories/smile.jpg',
    },
    {
      categoryID: 8,
      word: 'Laugh',
      translation: 'Смех',
      urlToAudio: './assets/audio/laugh.mp3',
      urlToImg: './assets/img/categories/laugh.jpg',
    },
  ],
};
